#nullable enable

namespace VehicleSales;

// Could be generated by a source generator
public partial class Job
{
  // Declaration of the partial property (C# 13)
  // Get-only property (C# 6)
  public partial bool isOnCommission { get; }

  public string Title
  {
    get => field;
    set
    {
      if (!string.Equals(field, value, StringComparison.Ordinal))
      {
        field = value;
        OnPropertyChanged(nameof(Title));
      }
    }
  }

  public string Department
  {
    get => field;
    set
    {
      if (!string.Equals(field, value, StringComparison.Ordinal))
      {
        field = value;
        OnPropertyChanged(nameof(Department));
        CalculateMaxVacationDays();
      }
    }
  }

  public decimal Salary
  {
    get => field;
    set
    {
      if (field != value)
      {
        field = value;
        OnPropertyChanged(nameof(Salary));
      }
    }
  }

  public int MaxVacationDays
  {
    get => field;
    private set
    {
      if (field != value)
      {
        field = value;
        OnPropertyChanged(nameof(MaxVacationDays));
      }
    }
  }

  // Declaration of the partial method
  partial void CalculateMaxVacationDays();

  // Declarations of the partial constructor
  public partial Job();
  public partial Job(string title, string department, decimal salary);

  // Declaration of the partial event
  public partial event PropertyChangedEventHandler? PropertyChanged;

}
