#nullable enable
using System;
using System.ComponentModel;

namespace VehicleSales;

// Could be generated by a source generator
public partial class Job
{
  public string? Title
  {
    get => field;
    set
    {
      if (!string.Equals(field, value, StringComparison.Ordinal))
      {
        field = value;
        OnPropertyChanged(nameof(Title));
      }
    }
  }

  public string? Department
  {
    get => field;
    set
    {
      if (!string.Equals(field, value, StringComparison.Ordinal))
      {
        field = value;
        OnPropertyChanged(nameof(Department));
        CalculateMaxVacationDays();
      }
    }
  }

  public decimal? Salary
  {
    get => field;
    set
    {
      if (field != value)
      {
        field = value;
        OnPropertyChanged(nameof(Salary));
      }
    }
  }

  public int? MaxVacationDays
  {
    get => field;
    set
    {
      if (field != value)
      {
        field = value;
        OnPropertyChanged(nameof(MaxVacationDays));
      }
    }
  }

  // Declaration of the partial method
  public partial void CalculateMaxVacationDays();

  // Declarations of the partial constructor
  public partial Job();
  public partial Job(string title, string department, decimal salary);

  // Implementation of the partial event
  private PropertyChangedEventHandler? _propertyChanged;
  public partial event PropertyChangedEventHandler? PropertyChanged
  {
    add { _propertyChanged += value; }
    remove { _propertyChanged -= value; }
  }

  // The raiser
  protected void OnPropertyChanged(string propertyName) =>
      _propertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));

}
